import React from "react";
import {
    Document,
    Page,
    Text,
    View,
    StyleSheet,
    Font,
    renderToBuffer,
} from "@react-pdf/renderer";
import { marked } from "marked";

// Register fonts
Font.register({
    family: "Inter",
    fonts: [
        { src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hjp-Ek-_EeA.woff" }, // Regular
        { src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hjp-Ek-_EeA.woff", fontWeight: "bold" }, // Bold
    ],
});

// Create styles
const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: "Inter",
        fontSize: 10,
        color: "#1e293b",
        backgroundColor: "#ffffff",
    },
    header: {
        marginBottom: 20,
        paddingBottom: 10,
        borderBottomWidth: 2,
        borderBottomColor: "#10b981",
        borderBottomStyle: "solid",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#065f46",
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 12,
        color: "#64748b",
    },
    section: {
        marginBottom: 16,
    },
    h2: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#0f172a",
        marginBottom: 8,
        marginTop: 12,
        backgroundColor: "#f1f5f9",
        padding: 6,
    },
    p: {
        marginBottom: 6,
        lineHeight: 1.4,
    },
    strong: {
        fontWeight: "bold",
    },
    table: {
        display: "flex",
        flexDirection: "column",
        width: "auto",
        borderStyle: "solid",
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRightWidth: 0,
        borderBottomWidth: 0,
        marginBottom: 12,
    },
    tableRow: {
        margin: "auto",
        flexDirection: "row",
    },
    tableCol: {
        width: "50%",
        borderStyle: "solid",
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: "#cbd5e1",
    },
    tableCol3: {
        width: "33.33%",
        borderStyle: "solid",
        borderWidth: 1,
        borderLeftWidth: 0,
        borderTopWidth: 0,
        borderColor: "#cbd5e1",
    },
    tableCellHeader: {
        margin: 5,
        fontSize: 10,
        fontWeight: "bold",
        color: "#334155",
    },
    tableCell: {
        margin: 5,
        fontSize: 10,
    },
    flagContainer: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 15,
    },
    flagBox: {
        width: "48%",
        padding: 10,
        borderWidth: 1,
        borderRadius: 4,
    },
    redFlagBox: {
        borderColor: "#fca5a5",
        backgroundColor: "#fef2f2",
    },
    greenFlagBox: {
        borderColor: "#86efac",
        backgroundColor: "#f0fdf4",
    },
    flagTitle: {
        fontSize: 12,
        fontWeight: "bold",
        marginBottom: 8,
    },
    redFlagTitle: { color: "#b91c1c" },
    greenFlagTitle: { color: "#15803d" },
    footer: {
        position: "absolute",
        bottom: 30,
        left: 40,
        right: 40,
        fontSize: 8,
        color: "#94a3b8",
        textAlign: "center",
        borderTopWidth: 1,
        borderTopColor: "#e2e8f0",
        paddingTop: 10,
    },
});

/**
 * Parse the structured markdown report into a data object for PDF rendering.
 * The markdown is deterministic, generated by analyst.ts buildMarkdownReport().
 */
function parseReportData(markdown: string) {
    const data: any = {
        title: "",
        founderProfile: [],
        solutionSnapshot: [],
        attachments: { pitchDeck: "", website: "" },
        scorecard: [],
        redFlags: [],
        greenFlags: [],
        missionFit: {},
        verdict: {},
    };

    // Extract title
    const titleMatch = markdown.match(/# INDIAAI MISSION STARTUP EVALUATION \| (.*)/);
    if (titleMatch) data.title = titleMatch[1];

    // Helper: extract a named section by heading
    const getSection = (heading: string): string => {
        const pattern = new RegExp(`## ${heading.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[^\n]*\n([\\s\\S]*?)(?=\n## |END OF REPORT|$)`);
        const match = markdown.match(pattern);
        return match ? match[1].trim() : "";
    };

    // Parse table rows from a section
    const parseTable = (section: string): Array<{ field: string; value: string }> => {
        const rows: Array<{ field: string; value: string }> = [];
        const lines = section.split("\n");
        let inTable = false;
        for (const line of lines) {
            if (line.includes("| Field | Details |") || line.includes("| Zone | Score |")) { inTable = true; continue; }
            if (line.includes("|---|")) continue;
            if (inTable && line.startsWith("|")) {
                const parts = line.split("|").map(s => s.trim()).filter(Boolean);
                if (parts.length >= 2) rows.push({ field: parts[0].replace(/\*\*/g, ""), value: parts.slice(1).join(" | ") });
            }
        }
        return rows;
    };

    // Section 1: Founder Profile
    data.founderProfile = parseTable(getSection("SECTION 1"));

    // Section 2: Solution Snapshot
    data.solutionSnapshot = parseTable(getSection("SECTION 2"));

    // Attachments
    const attachSection = getSection("ATTACHMENTS");
    const pitchMatch = attachSection.match(/\*\*Pitch Deck:\*\*\s*(.*)/);
    if (pitchMatch) data.attachments.pitchDeck = pitchMatch[1].trim();
    const webMatch = attachSection.match(/\*\*Website:\*\*\s*(.*)/);
    if (webMatch) data.attachments.website = webMatch[1].trim();

    // Section 3: Scorecard
    const scorecardSection = getSection("SECTION 3");
    const scorecardLines = scorecardSection.split("\n");
    let inTable = false;
    for (const line of scorecardLines) {
        if (line.includes("| Zone | Score | Analyst Note |")) { inTable = true; continue; }
        if (line.includes("|---|")) continue;
        if (inTable && line.startsWith("|")) {
            const parts = line.split("|").map(s => s.trim()).filter(Boolean);
            if (parts.length >= 3) data.scorecard.push({ zone: parts[0], score: parts[1], note: parts[2] });
        }
    }

    // Section 4: Flags (bullet points)
    const flagsSection = getSection("SECTION 4");
    const redMatch = flagsSection.match(/### 🔴 RED FLAGS\n([\s\S]*?)(?=\n### |$)/);
    if (redMatch) {
        data.redFlags = redMatch[1].split("\n")
            .filter((l: string) => l.startsWith("- "))
            .map((l: string) => l.substring(2).trim());
    }
    const greenMatch = flagsSection.match(/### 🟢 GREEN FLAGS\n([\s\S]*?)(?=\n### |$)/);
    if (greenMatch) {
        data.greenFlags = greenMatch[1].split("\n")
            .filter((l: string) => l.startsWith("- "))
            .map((l: string) => l.substring(2).trim());
    }

    // Section 5: Mission Fit
    const missionTitleMatch = markdown.match(/## SECTION 5 — AI MISSION FIT \((.*?)\)/);
    if (missionTitleMatch) data.missionFit.verdict = missionTitleMatch[1];
    const missionSection = getSection("SECTION 5");
    const pillarMatch = missionSection.match(/\*\*IndiaAI Pillar:\*\*\s*(.*)/);
    if (pillarMatch) data.missionFit.pillar = pillarMatch[1].trim();
    const awarenessMatch = missionSection.match(/\*\*IndiaAI Mission Awareness:\*\*\s*(.*)/);
    if (awarenessMatch) data.missionFit.awareness = awarenessMatch[1].trim();
    const reasoningMatch = missionSection.match(/\*\*Reasoning:\*\*\s*([\s\S]*?)(?=\n\n|$)/);
    if (reasoningMatch) data.missionFit.reasoning = reasoningMatch[1].trim();

    // Section 6: Verdict
    const verdictTitleMatch = markdown.match(/## SECTION 6 — AI VERDICT \[(.*?)\]/);
    if (verdictTitleMatch) data.verdict.verdict = verdictTitleMatch[1];
    const verdictSection = getSection("SECTION 6");
    const vReasonMatch = verdictSection.match(/\*\*Reasoning:\*\*\s*([\s\S]*?)(?=\n\n|$)/);
    if (vReasonMatch) data.verdict.reasoning = vReasonMatch[1].trim();

    return data;
}

// Sub-components
const StripMarkdown = ({ text }: { text: string }) => {
    // Strip markdown bold asterisks and <br> tags for standard text elements
    if (!text) return null;
    let clean = text.replace(/\*\*/g, "").replace(/<br>/g, "\n");
    // Strip emojis since React-PDF basic fonts don't support them well
    clean = clean.replace(/[🔴🟢]/g, "").trim();
    return <Text>{clean}</Text>;
};

const cleanField = (field: string) => {
    // Removes things like "[Try to keep it as close as possible...]" or "[1 line]"
    return field.replace(/\[.*?\]/g, "").trim();
};

const ReportTemplate = ({ markdown }: { markdown: string }) => {
    const data = parseReportData(markdown);

    return (
        <Document>
            <Page size="A4" style={styles.page} wrap>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>IndiaAI Mission</Text>
                    <Text style={styles.subtitle}>Startup Evaluation Report | {data.title}</Text>
                </View>

                {/* Section 1 */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 1 — FOUNDER PROFILE</Text>
                    <View style={styles.table}>
                        {data.founderProfile.map((row: any, i: number) => (
                            <View style={styles.tableRow} key={i}>
                                <View style={[styles.tableCol, { width: "30%" }]}>
                                    <Text style={styles.tableCellHeader}>{cleanField(row.field)}</Text>
                                </View>
                                <View style={[styles.tableCol, { width: "70%" }]}>
                                    <Text style={styles.tableCell}><StripMarkdown text={row.value} /></Text>
                                </View>
                            </View>
                        ))}
                    </View>
                </View>

                {/* Section 2 */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 2 — SOLUTION SNAPSHOT</Text>
                    <View style={styles.table}>
                        {data.solutionSnapshot.map((row: any, i: number) => (
                            <View style={styles.tableRow} key={i}>
                                <View style={[styles.tableCol, { width: "30%" }]}>
                                    <Text style={styles.tableCellHeader}>{cleanField(row.field)}</Text>
                                </View>
                                <View style={[styles.tableCol, { width: "70%" }]}>
                                    <Text style={styles.tableCell}><StripMarkdown text={row.value} /></Text>
                                </View>
                            </View>
                        ))}
                    </View>
                </View>

                {/* Section 3 */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 3 — 5-ZONE SCORECARD [PASS / MODERATE / FAIL]</Text>
                    <View style={styles.table}>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol3, { width: "20%" }]}><Text style={styles.tableCellHeader}>Zone</Text></View>
                            <View style={[styles.tableCol3, { width: "20%" }]}><Text style={styles.tableCellHeader}>Score</Text></View>
                            <View style={[styles.tableCol3, { width: "60%" }]}><Text style={styles.tableCellHeader}>Analyst Note</Text></View>
                        </View>
                        {data.scorecard.map((row: any, i: number) => (
                            <View style={styles.tableRow} key={i}>
                                <View style={[styles.tableCol3, { width: "20%" }]}><Text style={styles.tableCellHeader}>{row.zone}</Text></View>
                                <View style={[styles.tableCol3, { width: "20%" }]}>
                                    <Text style={[styles.tableCell, { fontWeight: "bold", color: row.score === "PASS" ? "#10b981" : row.score === "FAIL" ? "#ef4444" : "#f59e0b" }]}>
                                        {row.score}
                                    </Text>
                                </View>
                                <View style={[styles.tableCol3, { width: "60%" }]}><Text style={styles.tableCell}><StripMarkdown text={row.note} /></Text></View>
                            </View>
                        ))}
                    </View>
                </View>

                {/* Section 4 — Flags as bullet points */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 4 — FLAGS</Text>
                    <View style={styles.flagContainer}>
                        <View style={[styles.flagBox, styles.redFlagBox]}>
                            <Text style={[styles.flagTitle, styles.redFlagTitle]}>RED FLAGS</Text>
                            {data.redFlags.length > 0 ? data.redFlags.map((flag: string, i: number) => (
                                <Text style={styles.p} key={i}>• {flag}</Text>
                            )) : <Text style={styles.p}>• None</Text>}
                        </View>
                        <View style={[styles.flagBox, styles.greenFlagBox]}>
                            <Text style={[styles.flagTitle, styles.greenFlagTitle]}>GREEN FLAGS</Text>
                            {data.greenFlags.length > 0 ? data.greenFlags.map((flag: string, i: number) => (
                                <Text style={styles.p} key={i}>• {flag}</Text>
                            )) : <Text style={styles.p}>• None</Text>}
                        </View>
                    </View>
                </View>

                {/* Section 5 */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 5 — AI MISSION FIT (HIGH / MEDIUM / LOW)</Text>
                    <View style={styles.table}>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol, { width: "30%" }]}><Text style={styles.tableCellHeader}>IndiaAI Pillar</Text></View>
                            <View style={[styles.tableCol, { width: "70%" }]}><Text style={styles.tableCell}><StripMarkdown text={data.missionFit.pillar} /></Text></View>
                        </View>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol, { width: "30%" }]}><Text style={styles.tableCellHeader}>Awareness & Alignment</Text></View>
                            <View style={[styles.tableCol, { width: "70%" }]}><Text style={styles.tableCell}><StripMarkdown text={data.missionFit.awareness} /></Text></View>
                        </View>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol, { width: "30%" }]}><Text style={styles.tableCellHeader}>Reasoning</Text></View>
                            <View style={[styles.tableCol, { width: "70%" }]}><Text style={styles.tableCell}><StripMarkdown text={data.missionFit.reasoning} /></Text></View>
                        </View>
                    </View>
                    <View style={{ marginTop: 10, padding: 8, backgroundColor: data.missionFit.verdict === "HIGH" ? "#dcfce7" : data.missionFit.verdict === "LOW" ? "#fee2e2" : "#fef9c3", borderRadius: 6, alignItems: "center" }}>
                        <Text style={{ fontSize: 14, fontWeight: "bold", color: data.missionFit.verdict === "HIGH" ? "#16a34a" : data.missionFit.verdict === "LOW" ? "#dc2626" : "#ca8a04" }}>
                            {data.missionFit.verdict || "TBD"}
                        </Text>
                    </View>
                </View>

                {/* Section 6 */}
                <View style={styles.section} wrap={false}>
                    <Text style={styles.h2}>SECTION 6 — AI VERDICT</Text>
                    <View style={styles.table}>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol, { width: "30%" }]}><Text style={styles.tableCellHeader}>Verdict</Text></View>
                            <View style={[styles.tableCol, { width: "70%" }]}>
                                <Text style={[styles.tableCell, { fontWeight: "bold", color: data.verdict.verdict?.includes("GOOD FIT") ? "#10b981" : data.verdict.verdict?.includes("UNSURE") ? "#f59e0b" : "#ef4444" }]}>
                                    {data.verdict.verdict}
                                </Text>
                            </View>
                        </View>
                        <View style={styles.tableRow}>
                            <View style={[styles.tableCol, { width: "30%" }]}><Text style={styles.tableCellHeader}>Reasoning</Text></View>
                            <View style={[styles.tableCol, { width: "70%" }]}><Text style={styles.tableCell}><StripMarkdown text={data.verdict.reasoning} /></Text></View>
                        </View>
                    </View>
                </View>

                {/* Footer Component */}
                <Text style={styles.footer} fixed>
                    Generated by ITEL Foundation AI • This is a preliminary screening report
                </Text>
            </Page>
        </Document>
    );
};

export async function generateReportPDFBuffer(markdown: string): Promise<Buffer> {
    try {
        const doc = <ReportTemplate markdown={markdown} />;
        const buffer = await renderToBuffer(doc);
        return buffer;
    } catch (e) {
        console.error("PDF generation failed, returning text fallback buffer:", e);
        return Buffer.from(markdown, "utf-8");
    }
}
