import nodemailer from "nodemailer";

interface SendReportEmailParams {
  recipientEmail: string;
  pdfBuffer: Buffer;
  conversationTitle: string;
  conversationId: number;
  companyName?: string;
}

/**
 * Send a FounderCheck report email with a PDF attachment.
 * Transporter and config are created at call time so env vars are guaranteed to be loaded.
 */
export async function sendReportEmail({
  recipientEmail,
  pdfBuffer,
  conversationTitle,
  conversationId,
  companyName,
}: SendReportEmailParams): Promise<boolean> {
  // Read env vars at call time — NOT at module load time
  const smtpUser = process.env.SMTP_USERNAME;
  const smtpPass = process.env.SMTP_PASSWORD;
  const smtpHost = process.env.SMTP_SERVER || "smtp.gmail.com";
  const smtpPort = Number(process.env.SMTP_PORT) || 587;

  const isConfigured = Boolean(smtpUser && smtpPass);
  const displayName = companyName || "Startup";
  const dateStr = new Date().toISOString().split("T")[0];
  const filename = companyName
    ? `${companyName.replace(/\s+/g, "-")}-${dateStr}.pdf`
    : `FounderCheck-Report-${conversationId}-${dateStr}.pdf`;

  if (!isConfigured) {
    console.log(`⚠️  EMAIL CONFIG MISSING — Would send to: ${recipientEmail}`);
    console.log(`📧 Subject: FounderCheck ${displayName} Analysis Report`);
    console.log(`📎 Attachment: ${filename} (${pdfBuffer.length.toLocaleString()} bytes)`);
    console.log(`   SMTP_USERNAME=${smtpUser ?? "undefined"}, SMTP_PASSWORD=${smtpPass ? "set" : "undefined"}`);
    return true;
  }

  // Create transporter at call time with live env vars
  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: false, // STARTTLS
    auth: {
      user: smtpUser,
      pass: smtpPass,
    },
  });

  const recipients = recipientEmail.split(",").map((e) => e.trim()).filter(Boolean);

  const fromString = process.env.FROM_EMAIL
    ? `"${process.env.FROM_NAME || "FounderCheck"}" <${process.env.FROM_EMAIL}>`
    : `"FounderCheck Reports" <${smtpUser}>`;

  try {
    await transporter.sendMail({
      from: fromString,
      to: recipients.join(", "),
      subject: `FounderCheck ${displayName} Analysis Report - Session #${conversationId} - ${conversationTitle}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #2c3e50;">FounderCheck Startup Analysis Report</h1>
          <p>Dear Review Team,</p>
          <p>A new business validation session has been completed. Please find the report attached.</p>
          <div style="background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0;">
            <h3 style="margin-top: 0;">Session Details:</h3>
            <ul>
              <li><strong>Session ID:</strong> #${conversationId}</li>
              <li><strong>Title:</strong> ${conversationTitle}</li>
              <li><strong>Generated:</strong> ${new Date().toISOString()}</li>
            </ul>
          </div>
          <div style="background: #e8f4fd; padding: 15px; border-left: 4px solid #2196F3; margin: 20px 0;">
            <p style="margin: 0; color: #1565C0;">
              <strong>Note:</strong> This report was automatically generated upon session completion.
            </p>
          </div>
          <hr style="margin: 30px 0;" />
          <p style="color: #666; font-size: 12px;">
            Automatically generated by FounderCheck AI System.
          </p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: pdfBuffer,
          contentType: "application/pdf",
        },
      ],
    });

    console.log(`📧 Email sent successfully to ${recipients.join(", ")}`);
    return true;
  } catch (error) {
    console.error("❌ Error sending email:", error);
    return false;
  }
}
