import { config } from "dotenv";
import { resolve } from "path";
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), ".env.local"), override: true });
import { SQSClient, ReceiveMessageCommand, DeleteMessageCommand, Message } from "@aws-sdk/client-sqs";
import { supabase } from "../lib/supabase";
import { runAnalyst } from "../agents/analyst";
import { buildSkepticSummary } from "../agents/skeptic";
import { sendReportEmail } from "../lib/email";
import { generateReportPDFBuffer } from "../components/ReportPDF";

const sqsClient = new SQSClient({
  region: process.env.AWS_REGION || "ap-south-1",
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || "",
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || "",
  },
});

const queueUrl = process.env.AWS_SQS_QUEUE_URL;

async function processMessage(message: Message) {
  if (!message.Body) return;

  try {
    const { name, data: eventData } = JSON.parse(message.Body);
    console.log(`[Worker] Received task: ${name}`);

    if (name === "interview/report_ready") {
      // Report already generated by analyze-trigger.ts — just store and email
      const { conversationId, conversationTitle, companyName, reportMarkdown } = eventData as {
        conversationId: number;
        conversationTitle: string;
        companyName?: string;
        reportMarkdown: string;
      };

      console.log(`[Worker] Storing report for convId: ${conversationId}`);

      // 1. Store report
      await supabase.from("messages").insert({
        conversation_id: conversationId,
        role: "system",
        content: reportMarkdown,
      });

      // 2. Send email with PDF
      const recipientEmail = process.env.REPORT_RECIPIENT_EMAIL;
      if (recipientEmail) {
        const pdfBuffer = await generateReportPDFBuffer(reportMarkdown);
        await sendReportEmail({
          recipientEmail,
          pdfBuffer,
          conversationTitle,
          conversationId,
          companyName,
        });
        console.log(`[Worker] Email sent for convId: ${conversationId}`);
      } else {
        console.warn(`[Worker] REPORT_RECIPIENT_EMAIL not set — skipping email for convId: ${conversationId}`);
      }

      console.log(`[Worker] Done — report stored for convId: ${conversationId}`);

    } else if (name === "interview/finalize") {
      const { conversationId, conversationTitle } = eventData as {
        conversationId: number;
        conversationTitle: string;
      };

      console.log(`[Worker] Finalizing interview for convId: ${conversationId}`);

      // 1. Fetch conversation transcript
      const { data: messages, error: msgError } = await supabase
        .from("messages")
        .select("role, content, created_at")
        .eq("conversation_id", conversationId)
        .order("created_at", { ascending: true });

      if (msgError) throw new Error(`Failed to fetch messages: ${msgError.message}`);
      const transcript = messages || [];

      // 2. Fetch interview state
      const { data: interviewState, error: stateError } = await supabase
        .from("interview_states")
        .select("red_flags, green_flags, conversation_summary, vague_topics, pitch_deck_url")
        .eq("conversation_id", conversationId)
        .maybeSingle();

      if (stateError || !interviewState) {
        throw new Error(`Failed to fetch interview state: ${stateError?.message || "Not found"}`);
      }

      // 3. Run Analyst
      const conversationHistory = transcript.map((m) => ({
        role: m.role,
        content: m.content,
      }));

      const convSummary = interviewState.conversation_summary || {};
      const pitchDeckUrl = interviewState.pitch_deck_url || undefined;
      const skepticSummary = buildSkepticSummary(
        interviewState.red_flags || [],
        interviewState.green_flags || []
      );

      const reportMarkdown = await runAnalyst({
        conversationHistory,
        skepticSummary,
        companyName: convSummary.company_name || undefined,
        pitchDeckUrl,
        websiteUrl: convSummary.website_url || undefined,
        vagueTopics: interviewState.vague_topics || [],
      });

      // 4. Store report
      await supabase.from("messages").insert({
        conversation_id: conversationId,
        role: "system",
        content: reportMarkdown,
      });

      // 5. Send email
      const recipientEmail = process.env.REPORT_RECIPIENT_EMAIL;
      if (recipientEmail) {
        const pdfBuffer = await generateReportPDFBuffer(reportMarkdown);
        const companyName = convSummary.company_name || undefined;

        await sendReportEmail({
          recipientEmail,
          pdfBuffer,
          conversationTitle,
          conversationId,
          companyName,
        });
      }

      // 6. Mark complete
      await supabase
        .from("conversations")
        .update({ status: "completed" })
        .eq("id", conversationId);

      console.log(`[Worker] Successfully finalized interview for convId: ${conversationId}`);
    }

    // Delete message after processing
    await sqsClient.send(new DeleteMessageCommand({
      QueueUrl: queueUrl,
      ReceiptHandle: message.ReceiptHandle,
    }));

  } catch (error) {
    console.error("[Worker] Error processing message:", error);
  }
}

async function startWorker() {
  if (!queueUrl) {
    console.error("AWS_SQS_QUEUE_URL is not defined");
    process.exit(1);
  }

  console.log("[Worker] SQS Worker started, listening on queue...");

  while (true) {
    try {
      const response = await sqsClient.send(new ReceiveMessageCommand({
        QueueUrl: queueUrl,
        MaxNumberOfMessages: 1,
        WaitTimeSeconds: 20, // Long polling
      }));

      if (response.Messages) {
        for (const message of response.Messages) {
          await processMessage(message);
        }
      }
    } catch (error) {
      console.error("[Worker] Error receiving messages:", error);
      await new Promise(resolve => setTimeout(resolve, 5000)); // Wait before retrying
    }
  }
}

startWorker();
